# Form implementation generated from reading ui file 'reg_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(343, 200)
        MainWindow.setMinimumSize(QtCore.QSize(343, 200))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.reg_grid = QtWidgets.QGridLayout()
        self.reg_grid.setObjectName("reg_grid")
        self.check_name = QtWidgets.QPushButton(parent=self.centralwidget)
        self.check_name.setStyleSheet("background-color: rgb(255, 0, 127);")
        self.check_name.setObjectName("check_name")
        self.reg_grid.addWidget(self.check_name, 3, 0, 1, 2)
        self.reg = QtWidgets.QLabel(parent=self.centralwidget)
        self.reg.setMinimumSize(QtCore.QSize(269, 25))
        self.reg.setObjectName("reg")
        self.reg_grid.addWidget(self.reg, 0, 0, 1, 2)
        self.reg_enter = QtWidgets.QLabel(parent=self.centralwidget)
        self.reg_enter.setMinimumSize(QtCore.QSize(269, 13))
        self.reg_enter.setObjectName("reg_enter")
        self.reg_grid.addWidget(self.reg_enter, 1, 0, 1, 2)
        self.status = QtWidgets.QLabel(parent=self.centralwidget)
        self.status.setText("")
        self.status.setObjectName("status")
        self.reg_grid.addWidget(self.status, 4, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 19))
        self.lineEdit.setObjectName("lineEdit")
        self.reg_grid.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.reg_grid, 0, 0, 1, 1)
        self.send_room = QtWidgets.QPushButton(parent=self.centralwidget)
        self.send_room.setMinimumSize(QtCore.QSize(269, 17))
        self.send_room.setStyleSheet("background-color: rgb(255, 0, 127);")
        self.send_room.setObjectName("send_room")
        self.gridLayout.addWidget(self.send_room, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 283, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.check_name.setText(_translate("MainWindow", "Check name"))
        self.reg.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">REGISTRATION</span></p></body></html>"))
        self.reg_enter.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-style:italic;\">Enter your name</span></p></body></html>"))
        self.send_room.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
